Add License file
CityOfLosAngeles/angeleno-account-my-account pull request #21
Opened 2023-08-15 16:52 UTC by cbhernan

### What does this PR do?
Adds `LICENSE` file

### Which issue(s) is/are related to this PR?
This PR is related to issue(s)

Closes #16

2023-08-16 18:47 UTC, jaylenw requested changes
Hello @cbhernan , as long as you and your team is okay with the MIT license then I am okay. I will send two links for you to review regarding how dependencies may affect your licensing. I am hoping for this case it won't affect us and the MIT license will suffice.

I do think we should add a file extension to this filename, like how it is recommended by GitHub [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository). I'd prefer `.md`

2023-08-17 21:06 UTC, cbhernan commented
Thanks for all that information @jaylenw - I've gone through our direct dependencies and they're all either MIT or BSD-3-Clause, and no copyleft licenses so they're all compatible and we should be good. Also added the markdown extension.

2023-08-17 22:17 UTC, jaylenw approved these changes

2023-08-17 22:23 UTC, RV-LACity approved these changes

2023-08-22 18:23 UTC, merged